name: alot tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # we compile notmuch and new-style bindings from git master because
    # ubuntu-latest does not include the python3-notmuch2 package that alot needs.
    #   sudo apt-get -y install python3-notmuch2
    - name: Compile and install notmuch
      run: |
        # dependencies
        sudo apt-get update
        sudo apt-get install -y libxapian-dev libgmime-3.0-dev libtalloc-dev zlib1g-dev 
        sudo apt-get install -y swig libgpgme-dev dtach gpgsm python-cffi
        set -e

        # Clone the notmuch repository and move into it.
        git clone git://notmuchmail.org/git/notmuch --depth 1
        cd notmuch
        # Make and install the library.  
        ./configure \
                    --without-bash-completion \
                    --without-api-docs \
                    --without-emacs \
                    --without-desktop \
                    --without-ruby \
                    --without-zsh-completion
        make -j3 -l2
        sudo make install
        # Move out of the notmuch dir again.
        cd ../../..

    - name: Install notmuch2 python bindings
      run: |
        cd notmuch/bindings/python-cffi
        pip install .
        # Move out of the notmuch dir again.
        cd ../../..

        # test bindings
        python -c "import notmuch2"

    - name: Install alot's dependencies
      run: |
        sudo apt-get install -y gnupg2

        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with distutils
      run: |
        python setup.py test

# TODO: test with different python versions
# TODO: test docs generation
# TODO: upload coverage
